_welcome:
    pattern:  /
    defaults: { _controller: ForthicimeMedecinBundle:Medecin:index, page: 1 }

forthicime_admin:
    resource: "@ForthicimeAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

forthicime_client:
    resource: "@ForthicimeClientBundle/Resources/config/routing.yml"
    prefix:   /


forthicime_dossier:
    resource: "@ForthicimeDossierBundle/Resources/config/routing.yml"
    prefix:   /

forthicime_medecin:
    resource: "@ForthicimeMedecinBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:  /login
    defaults: { _controller: ForthicimeMedecinBundle:Medecin:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

admin_login:
     pattern:  /admin/login
     defaults: { _controller: ForthicimeAdminBundle:Default:login }

admin_login_check:
     pattern: /admin/login_check
     
admin_logout:
     pattern: /admin/logout
