forthicime_admin_homepage:
    pattern:  /
    defaults: { _controller: ForthicimeAdminBundle:Default:index }
forthicime_connection_count:
    pattern: /GetConnectionCount
    defaults: { _controller: ForthicimeAdminBundle:Default:GetConnectionCount}
forthicime_connection_count_month:
    pattern: /GetConnectionCountByMonth
    defaults: {_controller: ForthicimeAdminBundle:Default:GetConnectionCountByMonth}
forthicime_synchronization:
    pattern: /synchronization
    defaults: { _controller: ForthicimeAdminBundle:Synchronization:index }
Forthicime_Synchronization_detail:
    pattern: /synchronizationDetail/{category}/{synchronizationId}
    defaults: { _controller: ForthicimeAdminBundle:Synchronization:synchronizationDetail, category: "medecin", synchronizationId: 1 }